### ISSUE TITLE
error running npm start today

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/alchemylanguage-nodejs#60]
i git pull and:

	felipe@felipeurrego:~/alchemylanguage-nodejs$ npm start

	> alchemy-language-demo@0.2.5 start /home/felipe/alchemylanguage-nodejs
	> node server.js

	/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:34
		throw new Error('Argument error: api_key was not specified');
		^

	Error: Argument error: api_key was not specified
		at AlchemyLanguageV1.BaseServiceAlchemy.initCredentials (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:34:11)
		at AlchemyLanguageV1.BaseService (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service.js:39:18)
		at AlchemyLanguageV1.BaseServiceAlchemy (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:14:15)
		at new AlchemyLanguageV1 (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/alchemy-language/v1.js:80:22)
		at Object.<anonymous> (/home/felipe/alchemylanguage-nodejs/app.js:27:23)
		at Module._compile (module.js:409:26)
		at Object.Module._extensions..js (module.js:416:10)
		at Module.load (module.js:343:32)
		at Function.Module._load (module.js:300:12)
		at Module.require (module.js:353:17)

	npm ERR! Linux 4.2.0-27-generic
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
	npm ERR! node v4.4.4
	npm ERR! npm  v2.15.1
	npm ERR! code ELIFECYCLE
	npm ERR! alchemy-language-demo@0.2.5 start: `node server.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the alchemy-language-demo@0.2.5 start script 'node server.js'.
	npm ERR! This is most likely a problem with the alchemy-language-demo package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node server.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs alchemy-language-demo
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!
	npm ERR!     npm owner ls alchemy-language-demo
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/felipe/alchemylanguage-nodejs/npm-debug.log

How solved?

**Comment by germanattanasio** [comment]
Please read the instructions in the readme: https://github.com/watson-developer-cloud/alchemylanguage-nodejs#running-locally
