### ISSUE TITLE
cant deploy locally - Argument error: api_key was not specified

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/alchemylanguage-nodejs#65]
Hi bro

	sudo nano .env

	##
	# Environment variables
	API_KEY=XXX
	##

and this is error show me

	/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:35
		  throw new Error('Argument error: api_key was not specified');
		  ^

	Error: Argument error: api_key was not specified
		at AlchemyLanguageV1.BaseServiceAlchemy.initCredentials (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:35:13)
		at AlchemyLanguageV1.BaseService (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service.js:45:18)
		at AlchemyLanguageV1.BaseServiceAlchemy (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/lib/base_service_alchemy.js:15:15)
		at new AlchemyLanguageV1 (/home/felipe/alchemylanguage-nodejs/node_modules/watson-developer-cloud/alchemy-language/v1.js:80:22)
		at Object.<anonymous> (/home/felipe/alchemylanguage-nodejs/app.js:27:23)
		at Module._compile (module.js:409:26)
		at Object.Module._extensions..js (module.js:416:10)
		at Module.load (module.js:343:32)
		at Function.Module._load (module.js:300:12)
		at Module.require (module.js:353:17)

Im sure my key is correct

![key](https://cloud.githubusercontent.com/assets/428820/19413091/e0013c64-92e9-11e6-9ea5-dc671047226a.png)

How solve this?

**Comment by germanattanasio** [comment]
@johnfelipe you should not post your api key here. 

Regarding your issue. Try using `ALCHEMY_LANGUAGE_API_KEY` instead of `API_KEY`

**Comment by johnfelipe** [comment]
solved
